### ISSUE TITLE
Uncaught error with MetaMask manifest.json on launch

### ISSUE THREAD

**Issue by wbobeirne** [SwapyNetwork/electron-metamask-boilerplate#4]
Looks like the path to the manifest.json file is malformed, I get the following error on launch:

> Uncaught Exception:
> Error: ENOENT: no such file or directory, open '/Users/will/Documents/electron-metamask-boilerplate/extensions/metamask//manifest.json'

Note `metamask//manifest.json`. My system info is:
* Node 8.9.4
* NPM 5.7.1
* OSX 10.13.2

**Comment by icaroharry** [comment]
Hi! Thanks for letting us know.

I've just sent a fix for this. It might be related to the OSX path that works differently from Ubuntu. Anyway, now it's using `path.join` to resolve the manifest.json path. Try to get the lastest version from master.

Another thing that it worth to mention: I noticed that it was not explicit in the documentation that you need to manually download metamask and put it on `/extensions/metamask`. In case you didn't notice, we did a script to make this easier. Just run `npm run download.metamask.dev`
